# Generated by Django 4.1.5 on 2023-06-02 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='item',
        ),
    ]
